apiVersion: v2
name: kbot
description: A Helm chart for Telegram bot deployment on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - telegram
  - bot
  - go
maintainers:
  - name: prometheus-bot
home: https://github.com/yehormaksymchuk/prometheus-bot
